Jusung
six-and-extras/flower-flutter pull request #3
Opened 2019-09-26 05:16 UTC by jusung1459

added one line of code in main.dart
supposed to prevent resising. Cant duplicate the resizing so cant test

2019-09-26 05:33 UTC, kachen10 requested changes
This is odd, I don't think this file should be included.

2019-09-26 05:41 UTC, kachen10 reviewed
Can you please add these to .gitignore
.DS_Store
.atom/
.idea
.packages
.pub/
build/
ios/.generated/
packages
pubspec.lock
.flutter-plugins

2019-09-26 05:41 UTC, kachen10 commented on android/local.properties
> +sdk.dir=/home/jusung/Android/Sdk
I think .gitignore is not doing what we want it to do

2019-10-01 04:37 UTC, kachen10 approved these changes

2019-10-04 19:52 UTC, cl418 approved these changes

2019-10-05 17:08 UTC, merged